### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by PeakXing** [AverageAnime/create-food-1.20.1#1]
He crashes on my server, I don't know where the problem is, attached is my server mod list.
[latest.log](https://github.com/AverageAnime/create-food-1.20.1/files/13927938/latest.log)

**Comment by AverageAnime** [comment]
Thanks for the report. Fixed for the next update. 

It's a simple error on my part, so you can make the current version work by opening the .jar in WinRAR/7Zip and replacing the file 'createfood.mixins.json' with the new version from [here].

**Comment by PeakXing** [comment]
Thank you very much for your reply, I will test it

**Comment by PeakXing** [comment]
> Thanks for the report. Fixed for the next update.
> 
> It's a simple error on my part, so you can make the current version work by opening the .jar in WinRAR/7Zip and replacing the file 'createfood.mixins.json' with the new version from [here](https://github.com/AverageAnime/create-food-1.20.1/blob/1.20.1/src/main/resources/createfood.mixins.json).
Sorry, it doesn't work.
Before modifying it according to your plan, my client could start it and run it, but when I put it into the server, my server could not start, which is the error report you saw yesterday.
After I modified it according to your plan today, my client couldn't start, but when I disabled it, my client ran perfectly.

[crash-2024-01-14_09.14.25-client.txt](https://github.com/AverageAnime/create-food-1.20.1/files/13930013/crash-2024-01-14_09.14.25-client.txt)

**Comment by AverageAnime** [comment]
Sorry about that. I accidentally deleted a line. Use this one:
[createfood.mixins.json](https://github.com/AverageAnime/create-food-1.20.1/files/13930441/createfood.mixins.json)
