### ISSUE TITLE
Spice of Fabric compatibility issue

### ISSUE THREAD

**Issue by Blob336** [AverageAnime/create-food-1.20.1#14]
When put in a paper bag added by [Spice of Fabric](https://github.com/Siphalor/spiceoffabric), food items from Create:Food don't give comfort or nourishment effects. Farmer's Delight's food works fine.
____________________________________________________________

- Minecraft 1.20.1
- Fabric Loader 0.15.11
- cloth-config 11.1.118
- createfood 1.0.6
- fabric-api 0.92.1+1.20.1
- farmersdelight 1.20.1-2.1.1+refabricated
- spiceoffabric 1.6.2+mc1.20.1

**Comment by AverageAnime** [comment]
Unfortunately, I likely won't be able to fix this. Effects are normally added directly to items, which I assume SoF is looking for. With the tag system I use, effects are added via tag and not directly attached to the item. So, SoF can't see that there are effects attached to the item and therefore can't transfer the effects to the paper bag.
