### ISSUE TITLE
Some recipes seem to not work. (Fabric, MC 1.20.1, Mod Version 1.0.7)

### ISSUE THREAD

**Issue by NolanHewitt** [AverageAnime/create-food-1.20.1#15]
Minced Dragon, Donut Hole, Chocolate Donut Hole, Raw Strider Meatball, Raw Endermite Meatball, any of the four small meatball recipes, Breakfast Sausages, Chorus Fruit Slice, Diced Onion, Hash Browns, Sliced beetroot/carrot/potato/tomato, and Raw Ube Cake Base.

Looked at all of these recipes and comparing in game, the tags are all correct and I have all the items needed from other mods. Not sure what the issue causing the recipes to not activate in game is.

**Comment by AverageAnime** [comment]
Hash Browns - incorrectly uses the load conditions to disable when Create is present.
Raw Ube Cake Base - same as above + missing mixing recipe.
Raw Strider / Endermite Meatball - missing compacting recipe.

These are now fixed, but with the other items, I'm not seeing any issues.

**Comment by NolanHewitt** [comment]
Ah, for some reason literally all of my cutting recipes are disabled? I have no idea how or why.

**Comment by NolanHewitt** [comment]
Turns out it was the Item Obliterator mod for some reason. I'm glad at least a couple of them were actual issues that can be fixed now though.
