### ISSUE TITLE
Is it normal for me to get all these errors?

### ISSUE THREAD

**Issue by YOUNIN15** [AverageAnime/create-food-1.20.1#16]
In the registry I get a lot of errors related to recipes, I don't know if this is normal or if there is really a problem.

Fabric 1.20.1

I am using the latest version of the mod.

https://mclo.gs/dXRj3wa

https://api.mclo.gs/1/raw/dXRj3wa

![image](https://github.com/AverageAnime/create-food/assets/105389103/00be6d7c-a513-4178-9ea9-afda41841643)

**Comment by AverageAnime** [comment]
This is the result of items being disabled and recipes not understanding why there's an item that doesn't exist. It doesn't have any impact on gameplay, but I am working on fully utilizing fabric load conditions in recipes to remove this log spam.

**Comment by AverageAnime** [comment]
Fixed in 1.0.8.
