### ISSUE TITLE
Sausage and Cheese Biscuit bottom half can be turned into a worse food item.

### ISSUE THREAD

**Issue by NolanHewitt** [AverageAnime/create-food-1.20.1#17]
The same recipe makes both items, so in some crafting menus the worse item will be the result which is not as good as just the bottom half of the biscuit alone.
![huge_2024-06-04_01 19 36](https://github.com/AverageAnime/create-food/assets/52480898/d36a0ff7-5c94-4c2e-9cde-b4d24f9e429f)

**Comment by AverageAnime** [comment]
Thanks for the report. Fixed recipe is [here](https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/data/createfood/recipes/minecraft/crafting/cheese_biscuit_sandwich_from_crafting.json).
