### ISSUE TITLE
Milk Powder Dupe

### ISSUE THREAD

**Issue by S3lect3d** [AverageAnime/create-food-1.20.1#18]
milk powder dupe
![image](https://github.com/AverageAnime/create-food/assets/96404547/d6d0c0b8-f035-4a0f-bfc9-e5bd56da0d52)
![image](https://github.com/AverageAnime/create-food/assets/96404547/ede959f3-3b4b-42d3-b63b-b2b5d771623e)
![image](https://github.com/AverageAnime/create-food/assets/96404547/304df6e5-2a1a-4ae6-ac45-a9aed17be0ed)

**Comment by AverageAnime** [comment]
Fixed in 1.0.8
