### ISSUE TITLE
Salt Automation Issue

### ISSUE THREAD

**Issue by Sandshrew6** [AverageAnime/create-food-1.20.1#20]
Making salt in a basin has an output of water, which REI claims is the same amount as the input, but seems to actually be less (input of 125 mb vs output of ~83.3 mb). When in an automated system, the basin will be able to hold two buckets of water, the "input" and the "output," but will stop processing if the "output" is full. Due to the way pipes connected to basins work, I can't find a way to drain this "output" without the pipes pulling both the "input" and "output" water, and due to the water being partially consumed I can't just cycle the same water continuously, so either the system fills with water and the basin stops making salt, or the system eventually runs out of water. As a result, I can't automate salt production. Is this a bug, or is there a way around this that I'm missing?

**Comment by Sandshrew6** [comment]
A potential fix if the water IS meant to be partially consumed could be to add a "hot water" fluid that could be cooled by just mixing it without a blaze burner (like the hot chocolate fluids), as that could then be filtered by a smart fluid pipe to prevent the input from also being pulled.

**Comment by AverageAnime** [comment]
It seems I tried something that I didn't test. So, I've changed the recipe to a lower water input and removed the water output. Here's the [updated recipe](https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/data/createfood/recipes/create/mixing/salt_from_mixing_water.json). You should now be able to automate the production of salt with a constant supply of water. 
Also, REI showing the two as the same amount of fluid is just a visual bug and doesn't prevent recipes from working as intended. 
I don't think there's anything that I can do about it.
