### ISSUE TITLE
[Enhancement/Mod Support] My Nether's Delight 

### ISSUE THREAD

**Issue by Coolchilion** [AverageAnime/create-food-1.20.1#28]
Plans for My Nether's Delight compatibility? I just find that My Nether's Delight implementation is better than the original Nether's Delight, considering it is a reimagining by the same author of the original Nether's Delight.

https://www.curseforge.com/minecraft/mc-mods/my-nethers-delight

**Comment by AverageAnime** [comment]
Tags/recipes have been updated so that the magma cream marshmallow and raw strider meatball items can be made with My Nether's Delight items. If you have any other ideas for compatibility, please let me know.

**Comment by Coolchilion** [comment]
I will note that Hot Cream has the effects of burning all status effects and adding fire resistance and pungent, mentioning it because magma cream marshmallows does use Hot Cream.

![Screenshot 2024-09-17 144423](https://github.com/user-attachments/assets/6169fb74-5feb-4cb9-aa4b-02ebd12fc39e)
