### ISSUE TITLE
End's Delight Redundancy Intentional?

### ISSUE THREAD

**Issue by Coolchilion** [AverageAnime/create-food-1.20.1#30]
There seems to be some redundancy/same items when this mod is loaded with End's Delight. Items such as chorus popsicles, chorus fruit pie, and though not visually the same, chorus cookie. I was just wondering if this redundancy is intentional. If some items are supposed to be automatically disabled when both are loaded or if these items are left loaded to be disabled through the mod user's discretion.

![Screenshot 2024-09-15 170431](https://github.com/user-attachments/assets/e4b495e2-7ad1-4b15-8260-71fee8251af8)

**Comment by AverageAnime** [comment]
Yes. the overlap is intentional. In the Fabric version, you can disable overlapping items in the config, but on Forge, you will have to find another way. For either version, I also recommend [Almost Unified](https://www.curseforge.com/minecraft/mc-mods/almost-unified).
