### ISSUE TITLE
Juice are not consumable

### ISSUE THREAD

**Issue by liangmoe** [AverageAnime/create-food-1.20.1#34]
Every juice or bottle related foods are unusable, for example apple juice and Fruit Smoothie, im on forge 1.20.1, what happened?

**Comment by liangmoe** [comment]
also water bucket's tag is incorrect, should be `forge:buckets/water` i think

**Comment by AverageAnime** [comment]
Both are addressed in 1.1.3.

**Comment by liangmoe** [comment]
ginger cookie and ube cookie seems not craftable too even if i have ubes delight (also ube sweet dough)

**Comment by AverageAnime** [comment]
Ah, I was using the wrong tags. Fixed 1.1.3 now uploaded.
