### ISSUE TITLE
Vanilla Cake Inventory Texture is Broken

### ISSUE THREAD

**Issue by JasdanVM** [AverageAnime/create-food-1.20.1#39]
See for yourselves
![2024-10-11_19 15 49](https://github.com/user-attachments/assets/ff4bc4ba-4039-46fd-8864-731f8cbbe1de)
![2024-10-11_19 16 28](https://github.com/user-attachments/assets/e4e56f4c-bf73-4ddb-9b97-43222cfd4df2)

**Comment by AverageAnime** [comment]
Fixed in 1.1.4.
