### ISSUE TITLE
Chocolate Melting Violates Conservation of Mass

### ISSUE THREAD

**Issue by snakemasterepic** [AverageAnime/create-food-1.20.1#46]
* **Minecraft Version:** 1.20.1
* **Moad Loader & Version:** Forge 47.3.12
* **Create Food Version:** 1.1.5-Forge
# Description
There are several recipes that can be used to process chocolate, but their combined existence violates conservation of mass allowing chocolate to be produced from nothing.  In particular, the following loops exist:
* Liquid Chocolate -> Chocolate Bar -> Hollow Chocolate Bar -> Liquid Chocolate (Turns 250mb Liquid Chocolate into 500mb Liquid Chocolate)
* Liquid Dark Chocolate -> Dark Chocolate Bar -> Hollow Dark Chocolate Bar -> Liquid Dark Chocolate (Turns 333mb Liquid Dark Chocolate into 500mb Liquid Dark Chocolate)
* Liquid White Chocolate -> White Chocolate Bar -> Hollow White Chocolate Bar -> Liquid White Chocolate (Turns 333mb Liquid White Chocolate into 500mb Liquid White Chocolate)

**Comment by AverageAnime** [comment]
Should be resolved in 1.1.6.
