### ISSUE TITLE
Every recipe that has an amount defines it with a string

### ISSUE THREAD

**Issue by Luningor** [AverageAnime/create-food-1.20.1#47]
I have KubeJS installed (for a number of reasons) and one of the things that it does is say which recipes are malformed/broken. 
When I installed Create: Food, it pretty much filled the log with errors because Create: Food defines almost all it's recipes' Ints (like recipeTime, experience, etc) with strings (i.e.: instead of experience: 200,  experience: "200"):

Example: [19:45:25] [WARN] Failed to parse recipe 'createfood:create/mixing/gelatin_mix_fluid_from_mixing_heated_water[create:mixing]'! Falling back to vanilla: Expected amount to be a Int, was "1000"

I am currently testing if the issue nullifies the recipes or not, but it would be really neat if they were properly defined to prevent the console backlog.

**Comment by AverageAnime** [comment]
Fixed
