### ISSUE TITLE
Some recipes are impossible due to dough removal

### ISSUE THREAD

**Issue by danth** [AverageAnime/create-food-1.20.1#5]
This mod disables the recipe for Create dough here:

https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/data/create/recipes/crafting/appliances/dough.json

However, it's still needed to craft slimeballs:

![image](https://github.com/AverageAnime/create-food/assets/28959268/f4caf27c-3d51-42d1-b556-3bc9bf2a188e)

Or this variation of dumplings from Delightful Creators:

![image](https://github.com/AverageAnime/create-food/assets/28959268/29a72f2a-4cba-45e5-81e5-1b14f04a0014)

**Comment by danth** [comment]
My suggestion to solve this would be:

1. Remove Farmer's Delight wheat dough
2. Replace the Create dough recipe with the recipe for wheat dough, so it's consistent with the other doughs from this mod
3. Update cooking pot recipes to accept Create dough instead of wheat dough

Understandably this is a lot of effort, so a quicker fix would be to just enable both.

**Comment by AverageAnime** [comment]
Implemented some stuff to address this in the next update. 

For use with previous versions you can:

Replace slime ball recipe with one that uses 'c:dough' here:
https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/data/create/recipes/crafting/appliances/slime_ball.json

Add Farmer's Delight wheat dough to 'c:dough' here:
https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/data/c/tags/items/dough.json
This will allow Farmer's Delight wheat dough to be used in the Delightful Creators dumplings recipe.

For visual consistency, you can use a resource pack to change Farmer's Delight wheat dough to look like Create dough. This is included in the Farmer's Delight built-in resource pack in 1.0.5.
