### ISSUE TITLE
Does not recognize bacon or beef patties (1.0.5, Quilt, FD Refabricated)

### ISSUE THREAD

**Issue by Thrillville109** [AverageAnime/create-food-1.20.1#7]
![Screenshot 2024-04-10 215330](https://github.com/AverageAnime/create-food/assets/53126435/e5cb834c-e935-4130-9e2e-9c10102fed89)
As stated, neither beef patties nor bacon are recognized when making a burger. Issue also exists with regular fabric, tested with just Create, Create: Food, FD: Refabricated, and JEI.

**Comment by AverageAnime** [comment]
The problem is missing tags for beef patty and cooked bacon. Previously, these were added by Farmer's Delight, but these are missing in Refabricated. 
In the new version of 1.0.5 I just put out, I added the needed tags and fixed other recipes.

**Comment by Thrillville109** [comment]
Thank you.
