### ISSUE TITLE
[Bug] Dessert blocks not registered on server

### ISSUE THREAD

**Issue by Aiq0** [AverageAnime/create-food-1.20.1#8]
Dessert blocks can not be placed on multiplayer server, as they are only registered here:

https://github.com/AverageAnime/create-food/blob/3b36692de483d798d9800109a04caf459ebc5c69/src/main/java/net/averageanime/createfood/CreateFoodClient.java#L361-L442

And not here:

https://github.com/AverageAnime/create-food/blob/3b36692de483d798d9800109a04caf459ebc5c69/src/main/java/net/averageanime/createfood/CreateFood.java#L40

Blocks should be registered on both, client and server (it should work in singleplayer when only registered on client). It should be fixed by moving that part of code to `CreateFood.java`, however I did not had enough time to try it, so some testing is needed.

**Comment by AverageAnime** [comment]
Fixed in 1.0.6.
