### ISSUE TITLE
[1.20.1] Disabling items crashes server

### ISSUE THREAD

**Issue by druidicmage** [AverageAnime/create-food-1.20.1#9]
Disabling the suggested items in the config with the Lets Do and FD addons items causes the server to crash. I'm not sure if it's because I disabled suggested one, enabled the disabled items, or because of the new Farmer's Delight Refabricated port being available (maybe this mod is still using the Deprecated version), but something went wrong.

https://mclo.gs/YBntsKX

**Comment by AverageAnime** [comment]
1. Add these tags
https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/data/c/tags/items/compat_bun.json
&
https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/data/c/tags/items/compat_chocolate_cookie.json
2. Replace the existing recipes
https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/data/createfood/recipes/minecraft/campfire/bun_from_campfire.json
&
https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/data/createfood/recipes/minecraft/smelting/bun_from_smelting.json
&
https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/data/createfood/recipes/minecraft/smoking/bun_from_smoking.json
&
https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/data/createfood/recipes/minecraft/campfire/chocolate_cookie_from_campfire.json
&
https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/data/createfood/recipes/minecraft/smelting/chocolate_cookie_from_smelting.json
&
https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/data/createfood/recipes/minecraft/smoking/chocolate_cookie_from_smoking.json

I think this should fix the issues.
